"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import builtins
import google.protobuf.descriptor
import google.protobuf.internal.enum_type_wrapper
import google.protobuf.message
import sys
import typing

if sys.version_info >= (3, 10):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

class _EmailCategory:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _EmailCategoryEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_EmailCategory.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    CATEGORY_REPARATIONS: _EmailCategory.ValueType  # 0
    CATEGORY_ADMINISTRATION: _EmailCategory.ValueType  # 1
    CATEGORY_BILLING: _EmailCategory.ValueType  # 2
    CATEGORY_SPAM: _EmailCategory.ValueType  # 3

class EmailCategory(_EmailCategory, metaclass=_EmailCategoryEnumTypeWrapper): ...

CATEGORY_REPARATIONS: EmailCategory.ValueType  # 0
CATEGORY_ADMINISTRATION: EmailCategory.ValueType  # 1
CATEGORY_BILLING: EmailCategory.ValueType  # 2
CATEGORY_SPAM: EmailCategory.ValueType  # 3
global___EmailCategory = EmailCategory

@typing_extensions.final
class Email(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    TITLE_FIELD_NUMBER: builtins.int
    BODY_FIELD_NUMBER: builtins.int
    AUTHOR_FIELD_NUMBER: builtins.int
    CREATION_DATE_FIELD_NUMBER: builtins.int
    title: builtins.str
    body: builtins.str
    author: builtins.str
    creation_date: builtins.str
    def __init__(
        self,
        *,
        title: builtins.str = ...,
        body: builtins.str = ...,
        author: builtins.str = ...,
        creation_date: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["author", b"author", "body", b"body", "creation_date", b"creation_date", "title", b"title"]) -> None: ...

global___Email = Email

@typing_extensions.final
class EtlOutput(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    EMAILS_KEY_FIELD_NUMBER: builtins.int
    emails_key: builtins.str
    def __init__(
        self,
        *,
        emails_key: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["emails_key", b"emails_key"]) -> None: ...

global___EtlOutput = EtlOutput

@typing_extensions.final
class ClassificatorOutput(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    EMAIL_FIELD_NUMBER: builtins.int
    CATEGORY_FIELD_NUMBER: builtins.int
    @property
    def email(self) -> global___Email: ...
    category: global___EmailCategory.ValueType
    def __init__(
        self,
        *,
        email: global___Email | None = ...,
        category: global___EmailCategory.ValueType = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["email", b"email"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["category", b"category", "email", b"email"]) -> None: ...

global___ClassificatorOutput = ClassificatorOutput

@typing_extensions.final
class StatsStorerOutput(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    MESSAGE_FIELD_NUMBER: builtins.int
    message: builtins.str
    def __init__(
        self,
        *,
        message: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["message", b"message"]) -> None: ...

global___StatsStorerOutput = StatsStorerOutput
