// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.21.12
// source: internal_nodes.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EmailCategory int32

const (
	EmailCategory_CATEGORY_REPARATIONS    EmailCategory = 0
	EmailCategory_CATEGORY_ADMINISTRATION EmailCategory = 1
	EmailCategory_CATEGORY_BILLING        EmailCategory = 2
	EmailCategory_CATEGORY_SPAM           EmailCategory = 3
)

// Enum value maps for EmailCategory.
var (
	EmailCategory_name = map[int32]string{
		0: "CATEGORY_REPARATIONS",
		1: "CATEGORY_ADMINISTRATION",
		2: "CATEGORY_BILLING",
		3: "CATEGORY_SPAM",
	}
	EmailCategory_value = map[string]int32{
		"CATEGORY_REPARATIONS":    0,
		"CATEGORY_ADMINISTRATION": 1,
		"CATEGORY_BILLING":        2,
		"CATEGORY_SPAM":           3,
	}
)

func (x EmailCategory) Enum() *EmailCategory {
	p := new(EmailCategory)
	*p = x
	return p
}

func (x EmailCategory) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EmailCategory) Descriptor() protoreflect.EnumDescriptor {
	return file_internal_nodes_proto_enumTypes[0].Descriptor()
}

func (EmailCategory) Type() protoreflect.EnumType {
	return &file_internal_nodes_proto_enumTypes[0]
}

func (x EmailCategory) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EmailCategory.Descriptor instead.
func (EmailCategory) EnumDescriptor() ([]byte, []int) {
	return file_internal_nodes_proto_rawDescGZIP(), []int{0}
}

type Email struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Title        string `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Body         string `protobuf:"bytes,2,opt,name=body,proto3" json:"body,omitempty"`
	Author       string `protobuf:"bytes,3,opt,name=author,proto3" json:"author,omitempty"`
	CreationDate string `protobuf:"bytes,4,opt,name=creation_date,json=creationDate,proto3" json:"creation_date,omitempty"`
}

func (x *Email) Reset() {
	*x = Email{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_nodes_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Email) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Email) ProtoMessage() {}

func (x *Email) ProtoReflect() protoreflect.Message {
	mi := &file_internal_nodes_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Email.ProtoReflect.Descriptor instead.
func (*Email) Descriptor() ([]byte, []int) {
	return file_internal_nodes_proto_rawDescGZIP(), []int{0}
}

func (x *Email) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Email) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

func (x *Email) GetAuthor() string {
	if x != nil {
		return x.Author
	}
	return ""
}

func (x *Email) GetCreationDate() string {
	if x != nil {
		return x.CreationDate
	}
	return ""
}

type EtlOutput struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Email *Email `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
}

func (x *EtlOutput) Reset() {
	*x = EtlOutput{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_nodes_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EtlOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EtlOutput) ProtoMessage() {}

func (x *EtlOutput) ProtoReflect() protoreflect.Message {
	mi := &file_internal_nodes_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EtlOutput.ProtoReflect.Descriptor instead.
func (*EtlOutput) Descriptor() ([]byte, []int) {
	return file_internal_nodes_proto_rawDescGZIP(), []int{1}
}

func (x *EtlOutput) GetEmail() *Email {
	if x != nil {
		return x.Email
	}
	return nil
}

type ClassificatorOutput struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Email    *Email        `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Category EmailCategory `protobuf:"varint,2,opt,name=category,proto3,enum=main.EmailCategory" json:"category,omitempty"`
}

func (x *ClassificatorOutput) Reset() {
	*x = ClassificatorOutput{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_nodes_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ClassificatorOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClassificatorOutput) ProtoMessage() {}

func (x *ClassificatorOutput) ProtoReflect() protoreflect.Message {
	mi := &file_internal_nodes_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClassificatorOutput.ProtoReflect.Descriptor instead.
func (*ClassificatorOutput) Descriptor() ([]byte, []int) {
	return file_internal_nodes_proto_rawDescGZIP(), []int{2}
}

func (x *ClassificatorOutput) GetEmail() *Email {
	if x != nil {
		return x.Email
	}
	return nil
}

func (x *ClassificatorOutput) GetCategory() EmailCategory {
	if x != nil {
		return x.Category
	}
	return EmailCategory_CATEGORY_REPARATIONS
}

type StatsStorerOutput struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *StatsStorerOutput) Reset() {
	*x = StatsStorerOutput{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_nodes_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StatsStorerOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatsStorerOutput) ProtoMessage() {}

func (x *StatsStorerOutput) ProtoReflect() protoreflect.Message {
	mi := &file_internal_nodes_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatsStorerOutput.ProtoReflect.Descriptor instead.
func (*StatsStorerOutput) Descriptor() ([]byte, []int) {
	return file_internal_nodes_proto_rawDescGZIP(), []int{3}
}

func (x *StatsStorerOutput) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type BatchEtlOutput struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ObjectKey string `protobuf:"bytes,1,opt,name=object_key,json=objectKey,proto3" json:"object_key,omitempty"`
}

func (x *BatchEtlOutput) Reset() {
	*x = BatchEtlOutput{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_nodes_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BatchEtlOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchEtlOutput) ProtoMessage() {}

func (x *BatchEtlOutput) ProtoReflect() protoreflect.Message {
	mi := &file_internal_nodes_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchEtlOutput.ProtoReflect.Descriptor instead.
func (*BatchEtlOutput) Descriptor() ([]byte, []int) {
	return file_internal_nodes_proto_rawDescGZIP(), []int{4}
}

func (x *BatchEtlOutput) GetObjectKey() string {
	if x != nil {
		return x.ObjectKey
	}
	return ""
}

var File_internal_nodes_proto protoreflect.FileDescriptor

var file_internal_nodes_proto_rawDesc = []byte{
	0x0a, 0x14, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x5f, 0x6e, 0x6f, 0x64, 0x65, 0x73,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04, 0x6d, 0x61, 0x69, 0x6e, 0x22, 0x6e, 0x0a, 0x05,
	0x45, 0x6d, 0x61, 0x69, 0x6c, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x62,
	0x6f, 0x64, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x62, 0x6f, 0x64, 0x79, 0x12,
	0x16, 0x0a, 0x06, 0x61, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x06, 0x61, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x12, 0x23, 0x0a, 0x0d, 0x63, 0x72, 0x65, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x5f, 0x64, 0x61, 0x74, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c,
	0x63, 0x72, 0x65, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x44, 0x61, 0x74, 0x65, 0x22, 0x2e, 0x0a, 0x09,
	0x45, 0x74, 0x6c, 0x4f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x12, 0x21, 0x0a, 0x05, 0x65, 0x6d, 0x61,
	0x69, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x6d, 0x61, 0x69, 0x6e, 0x2e,
	0x45, 0x6d, 0x61, 0x69, 0x6c, 0x52, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x22, 0x69, 0x0a, 0x13,
	0x43, 0x6c, 0x61, 0x73, 0x73, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x6f, 0x72, 0x4f, 0x75, 0x74,
	0x70, 0x75, 0x74, 0x12, 0x21, 0x0a, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x6d, 0x61, 0x69, 0x6e, 0x2e, 0x45, 0x6d, 0x61, 0x69, 0x6c, 0x52,
	0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x12, 0x2f, 0x0a, 0x08, 0x63, 0x61, 0x74, 0x65, 0x67, 0x6f,
	0x72, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x13, 0x2e, 0x6d, 0x61, 0x69, 0x6e, 0x2e,
	0x45, 0x6d, 0x61, 0x69, 0x6c, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x52, 0x08, 0x63,
	0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x22, 0x2d, 0x0a, 0x11, 0x53, 0x74, 0x61, 0x74, 0x73,
	0x53, 0x74, 0x6f, 0x72, 0x65, 0x72, 0x4f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x12, 0x18, 0x0a, 0x07,
	0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x2f, 0x0a, 0x0e, 0x42, 0x61, 0x74, 0x63, 0x68, 0x45,
	0x74, 0x6c, 0x4f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x6f, 0x62, 0x6a, 0x65,
	0x63, 0x74, 0x5f, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x6f, 0x62,
	0x6a, 0x65, 0x63, 0x74, 0x4b, 0x65, 0x79, 0x2a, 0x6f, 0x0a, 0x0d, 0x45, 0x6d, 0x61, 0x69, 0x6c,
	0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x12, 0x18, 0x0a, 0x14, 0x43, 0x41, 0x54, 0x45,
	0x47, 0x4f, 0x52, 0x59, 0x5f, 0x52, 0x45, 0x50, 0x41, 0x52, 0x41, 0x54, 0x49, 0x4f, 0x4e, 0x53,
	0x10, 0x00, 0x12, 0x1b, 0x0a, 0x17, 0x43, 0x41, 0x54, 0x45, 0x47, 0x4f, 0x52, 0x59, 0x5f, 0x41,
	0x44, 0x4d, 0x49, 0x4e, 0x49, 0x53, 0x54, 0x52, 0x41, 0x54, 0x49, 0x4f, 0x4e, 0x10, 0x01, 0x12,
	0x14, 0x0a, 0x10, 0x43, 0x41, 0x54, 0x45, 0x47, 0x4f, 0x52, 0x59, 0x5f, 0x42, 0x49, 0x4c, 0x4c,
	0x49, 0x4e, 0x47, 0x10, 0x02, 0x12, 0x11, 0x0a, 0x0d, 0x43, 0x41, 0x54, 0x45, 0x47, 0x4f, 0x52,
	0x59, 0x5f, 0x53, 0x50, 0x41, 0x4d, 0x10, 0x03, 0x42, 0x09, 0x5a, 0x07, 0x2e, 0x2f, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_internal_nodes_proto_rawDescOnce sync.Once
	file_internal_nodes_proto_rawDescData = file_internal_nodes_proto_rawDesc
)

func file_internal_nodes_proto_rawDescGZIP() []byte {
	file_internal_nodes_proto_rawDescOnce.Do(func() {
		file_internal_nodes_proto_rawDescData = protoimpl.X.CompressGZIP(file_internal_nodes_proto_rawDescData)
	})
	return file_internal_nodes_proto_rawDescData
}

var file_internal_nodes_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_internal_nodes_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_internal_nodes_proto_goTypes = []interface{}{
	(EmailCategory)(0),          // 0: main.EmailCategory
	(*Email)(nil),               // 1: main.Email
	(*EtlOutput)(nil),           // 2: main.EtlOutput
	(*ClassificatorOutput)(nil), // 3: main.ClassificatorOutput
	(*StatsStorerOutput)(nil),   // 4: main.StatsStorerOutput
	(*BatchEtlOutput)(nil),      // 5: main.BatchEtlOutput
}
var file_internal_nodes_proto_depIdxs = []int32{
	1, // 0: main.EtlOutput.email:type_name -> main.Email
	1, // 1: main.ClassificatorOutput.email:type_name -> main.Email
	0, // 2: main.ClassificatorOutput.category:type_name -> main.EmailCategory
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_internal_nodes_proto_init() }
func file_internal_nodes_proto_init() {
	if File_internal_nodes_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_internal_nodes_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Email); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_nodes_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EtlOutput); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_nodes_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ClassificatorOutput); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_nodes_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StatsStorerOutput); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_nodes_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BatchEtlOutput); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_internal_nodes_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_internal_nodes_proto_goTypes,
		DependencyIndexes: file_internal_nodes_proto_depIdxs,
		EnumInfos:         file_internal_nodes_proto_enumTypes,
		MessageInfos:      file_internal_nodes_proto_msgTypes,
	}.Build()
	File_internal_nodes_proto = out.File
	file_internal_nodes_proto_rawDesc = nil
	file_internal_nodes_proto_goTypes = nil
	file_internal_nodes_proto_depIdxs = nil
}
