# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: internal_nodes.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14internal_nodes.proto\x12\x04main\"K\n\x05\x45mail\x12\r\n\x05title\x18\x01 \x01(\t\x12\x0c\n\x04\x62ody\x18\x02 \x01(\t\x12\x0e\n\x06\x61uthor\x18\x03 \x01(\t\x12\x15\n\rcreation_date\x18\x04 \x01(\t\"\x1f\n\tEtlOutput\x12\x12\n\nemails_key\x18\x01 \x01(\t\"X\n\x13\x43lassificatorOutput\x12\x1a\n\x05\x65mail\x18\x01 \x01(\x0b\x32\x0b.main.Email\x12%\n\x08\x63\x61tegory\x18\x02 \x01(\x0e\x32\x13.main.EmailCategory\"$\n\x11StatsStorerOutput\x12\x0f\n\x07message\x18\x01 \x01(\t*o\n\rEmailCategory\x12\x18\n\x14\x43\x41TEGORY_REPARATIONS\x10\x00\x12\x1b\n\x17\x43\x41TEGORY_ADMINISTRATION\x10\x01\x12\x14\n\x10\x43\x41TEGORY_BILLING\x10\x02\x12\x11\n\rCATEGORY_SPAM\x10\x03\x42\tZ\x07./protob\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'internal_nodes_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z\007./proto'
  _EMAILCATEGORY._serialized_start=268
  _EMAILCATEGORY._serialized_end=379
  _EMAIL._serialized_start=30
  _EMAIL._serialized_end=105
  _ETLOUTPUT._serialized_start=107
  _ETLOUTPUT._serialized_end=138
  _CLASSIFICATOROUTPUT._serialized_start=140
  _CLASSIFICATOROUTPUT._serialized_end=228
  _STATSSTOREROUTPUT._serialized_start=230
  _STATSSTOREROUTPUT._serialized_end=266
# @@protoc_insertion_point(module_scope)
